apiVersion: v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        apps: vprodb

    spec:
      containers:
      - name: vprodb
        image: vprocontainers/vprofiledb

        volumeMounts:
        - mountpath: /var/lib/mysql
          name: vpro-db-data

        ports:
        - name: vprodb-port
          containerPort: 3306
    
        env:
        - name: MYSQL_ROOT_PASSWORD
          valuefrom:
            secretKeyRef:
              name: my-secret
              key: db-pass


      volumes:
      - name: vpro-db-data
      persistentvolumeclaim:
        claimName: db-pv-claim

      init containers:
      - name: busybox
        image: busybox:latest
        command: ["sh","-c","rm -rf /var/lib/mysql/lost+found"]

        volumeMounts:
        - name: vpro-db-data
          mountpath: /var/lib/mysql






