apiVersion: v1
kind: persitent-volume claim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    request:
      storage: 3Gi
  StorageClassName: default      
                                               