apiVersion: v1
kind: Service
metadata:
  name: vprodb
  labels:
    app: vprodbservice

spec:
  type: ClusterIP
  ports:
  - targetPort: vprodb-port
    port: 3306
    protocol: TCP

  selector:
    apps: vprodb   
