apiVersion: v1
kind: Deployment
metadata:
  name: vpro-rmq
  labels:
    app: vpr-rmq
spec:
  selector:
    matchLabels:
      app: rmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
      - name: rabbitmq-container
        image: rabbitmq

      env:
      - name: RABBITMQ_DEFAULT_PASS
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: rmq-pass

      - name: RABBITMQ_DEFAULT_USER
        value: "guest"      

      ports:
      - name: rabbitmq-port
        containerPort: 5672

